server:
  endpoints: 
    - redis-server-1:6379
    - redis-server-2:6379
    - redis-server-3:6379
  ssl: false
  user: some_username
  password: strong_password
  service name: null             # optional, used for sentinel or clustered servers